catalogMode: prefer

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade

overrides:
  undici-types: 7.16.0
  vite: ^7.0.0

catalog:
  '@antfu/eslint-config': ^6.0.0
  '@tailwindcss/vite': ^4.1.14
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/vue': ^8.1.0
  '@types/node': ^24.3.0
  '@types/nprogress': ^0.2.3
  '@typescript-eslint/eslint-plugin': ^8.22.0
  '@unhead/vue': ^2.0.14
  '@vitejs/plugin-vue': ^6.0.1
  '@vitest/coverage-v8': ^4.0.15
  '@vitest/ui': ^4.0.15
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^13.8.0
  beasties: ^0.3.5
  dotenv: ^17.2.1
  eslint: ^9.34.0
  gray-matter: ^4.0.3
  happy-dom: ^20.0.11
  lint-staged: ^16.1.5
  markdown-it-prism: ^3.0.0
  nprogress: ^0.2.0
  pinia: ^3.0.3
  postcss-html: ^1.8.0
  prism-theme-vars: ^0.2.5
  rollup: ^4.52.4
  simple-git-hooks: ^2.11.1
  stylelint: ^16.23.1
  stylelint-config-recommended-vue: ^1.6.0
  stylelint-config-standard: ^39.0.0
  stylelint-order: ^7.0.0
  tailwindcss: ^4.1.14
  typescript: ^5.7.3
  unplugin-vue-markdown: ^29.1.0
  vite: ^7.1.9
  vite-plugin-compression: ^0.5.1
  vite-plugin-pages: ^0.33.1
  vite-plugin-pages-sitemap: ^1.7.1
  vite-plugin-vue-devtools: ^8.0.5
  vite-plugin-vue-layouts: ^0.11.0
  vite-ssg: ^28.2.2
  vitest: ^4.0.15
  vue: ^3.5.20
  vue-router: ^4.6.3
  vue-tsc: ^3.0.6
  vue3-recaptcha-v2: ^2.1.0
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - simple-git-hooks
