/**
 * @module data/mock-api
 * @description Mock API data and functions for development and SSG builds.
 * Provides in-memory data structures and async functions that simulate API calls.
 * Used to keep the starter self-contained without external dependencies.
 */

/**
 * @interface Guide
 * @description Guide/article data structure.
 */
export interface Guide {
  /** URL-friendly identifier for the guide */
  slug: string
  /** Guide title */
  title: string
  /** Short summary/description */
  summary: string
  /** Array of body paragraphs */
  body: string[]
  /** Array of tag strings */
  tags: string[]
  /** Last update date (ISO format) */
  updatedAt: string
}

/**
 * @interface Project
 * @description Project showcase data structure.
 */
export interface Project {
  /** URL-friendly identifier for the project */
  slug: string
  /** Project name */
  name: string
  /** Project description */
  description: string
  /** Technology stack used */
  stack: string[]
  /** Project status */
  status: 'planned' | 'in-progress' | 'shipped'
  /** Optional repository URL */
  repo?: string
  /** Link to project page or demo */
  href: string
}

/**
 * @function delay
 * @private
 * @description Simulates network delay for mock API calls.
 * @param {number} [ms] - Delay in milliseconds
 * @returns {Promise<void>} Promise that resolves after the delay
 */
function delay(ms = 120) {
  return new Promise(resolve => setTimeout(resolve, ms))
}

const guides: Guide[] = [
  {
    slug: 'file-based-routing',
    title: 'File-based + dynamic routing',
    summary: 'Add routes by dropping `.vue` or `.md` files in `src/pages`, including dynamic segments like `[slug].vue`.',
    body: [
      'Routes are generated by `vite-plugin-pages` using Nuxt-style semantics. Add `src/pages/guides/[slug].vue` to create a dynamic route.',
      'Use `definePageMeta` or `<route>` blocks for prerendering hints and per-page options.',
      'For SSG, include dynamic paths via data or fetch at runtime if the route list is unknown at build time.',
    ],
    tags: ['routing', 'vite-plugin-pages', 'ssg'],
    updatedAt: '2025-01-10',
  },
  {
    slug: 'ssg-data-fetching',
    title: 'Data fetching with SSG',
    summary: 'Combine `ViteSSG` + Pinia to hydrate stores during prerender and reuse them on the client.',
    body: [
      'Use stores to load data in `onBeforeMount`/`onMounted` for client-side fetches, or `onBeforeRender` hooks for prerendered runs.',
      'Store snapshots are serialized via `ctx.initialState` in `src/main.ts` to keep state in sync across SSR/SPA.',
      'Mock APIs live in `src/data/mock-api.ts` to keep the starter self-contained without external dependencies.',
    ],
    tags: ['vite-ssg', 'pinia', 'state'],
    updatedAt: '2025-01-10',
  },
  {
    slug: 'styling-tailwind',
    title: 'Styling with Tailwind v4',
    summary: 'Tailwind v4 is enabled through the official Vite plugin; use `@theme` tokens in `src/styles/main.css`.',
    body: [
      'Purge is automatic; author styles directly with utility classes.',
      'Global tokens (colors, fonts) are declared in `@theme` and consumed in components.',
      'Combine Tailwind utilities with small CSS helpers for cards, sections, and grids.',
    ],
    tags: ['tailwind', 'styling'],
    updatedAt: '2025-01-10',
  },
  {
    slug: 'markdown-pages',
    title: 'Writing pages in Markdown',
    summary: 'Create content-rich pages using Markdown syntax with frontmatter support, code highlighting, and Vue component integration.',
    body: [
      'This starter supports Markdown files (`.md`) as first-class routes. Simply drop a `.md` file in `src/pages` and it will be automatically converted to a route.',
      'Features include frontmatter support, syntax highlighting with Prism.js, Vue component integration, and SSG-friendly pre-rendering.',
      'Markdown content is automatically styled using Tailwind Typography and custom styles defined in `src/styles/markdown.css`.',
    ],
    tags: ['markdown', 'content', 'unplugin-vue-markdown'],
    updatedAt: '2025-01-10',
  },
]

const projects: Project[] = [
  {
    slug: 'starter-kit',
    name: 'Starter kit shell',
    description: 'Vue 3 + TypeScript + Vite SSG + Pinia with file-based routing and Markdown support.',
    stack: ['Vite', 'Vue 3', 'ViteSSG', 'Tailwind', 'Pinia'],
    status: 'shipped',
    href: '/guides/file-based-routing',
  },
  {
    slug: 'dynamic-content',
    name: 'Dynamic content demo',
    description: 'Showcases dynamic routes backed by a mock API plus hydrated Pinia stores.',
    stack: ['Vue Router', 'Pinia', 'Mock API'],
    status: 'shipped',
    href: '/guides/ssg-data-fetching',
  },
  {
    slug: 'composables',
    name: 'Composables examples',
    description: 'Practical examples of reusable composables: useFetch, useNotification, and useResponsive with live demos.',
    stack: ['Composables', 'Vue 3', 'TypeScript'],
    status: 'shipped',
    href: '/composables',
  },
  {
    slug: 'forms',
    name: 'Form handling patterns',
    description: 'Complete form examples with validation, submission, and error handling using Composition API.',
    stack: ['Forms', 'Validation', 'useFetch'],
    status: 'shipped',
    href: '/forms',
  },
  {
    slug: 'ui-playground',
    name: 'UI playground',
    description: 'Tailwind v4 + component primitives for headers, cards, and callouts.',
    stack: ['Tailwind', 'TypeScript'],
    status: 'shipped',
    href: '/ui-playground',
  },
]

/**
 * @function fetchGuides
 * @description Fetches all guides from the mock API.
 * @returns {Promise<Guide[]>} Array of all guides
 *
 * @example
 * ```typescript
 * const guides = await fetchGuides()
 * ```
 */
export async function fetchGuides() {
  await delay()
  return guides
}

/**
 * @function fetchGuideBySlug
 * @description Fetches a single guide by its slug.
 * @param {string} slug - Guide slug identifier
 * @returns {Promise<Guide | undefined>} Guide object or undefined if not found
 *
 * @example
 * ```typescript
 * const guide = await fetchGuideBySlug('file-based-routing')
 * ```
 */
export async function fetchGuideBySlug(slug: string) {
  await delay()
  return guides.find(guide => guide.slug === slug)
}

/**
 * @function fetchProjects
 * @description Fetches all projects from the mock API.
 * @returns {Promise<Project[]>} Array of all projects
 *
 * @example
 * ```typescript
 * const projects = await fetchProjects()
 * ```
 */
export async function fetchProjects() {
  await delay()
  return projects
}
